"""Randomly select 30 of the 250 SH-250 sampling-harness bots per model, without replacement, no filtering,
then split each model's 30 bots at random into three groups of 10 (A, B, C)."""
import json,random,re,secrets,collections,datetime,sys
from pathlib import Path
POOL='sh250-pool-5ac92bc7';N=30
EXCLUDE={'claude-opus-5-high','minimax-m3-high'}   # requested 2026-09-25; the draw still runs over all 23 models so the other models' picks are unchanged
HERE=Path(__file__).resolve().parent
# samples_index.json is the listing of the pool's sample folders (2026-09-25) reduced to slot numbers per model.
slots={k:set(v) for k,v in json.loads((HERE/'samples_index.json').read_text())['slots'].items()}
assert len(slots)==23 and all(s==set(range(250)) for s in slots.values()),{k:len(v) for k,v in slots.items()}
seed=int(sys.argv[1]) if len(sys.argv)>1 else secrets.randbits(64)   # one random number generated by code; recorded below for reproducibility
rng=random.Random(seed);selection={}
RUN_SIZE=50;chosen_run={}
for model in sorted(slots):
    runs=sorted({i//RUN_SIZE for i in slots[model]});assert runs==[0,1,2,3,4]
    run=rng.choice(runs);chosen_run[model]=run                      # one 50-slot run per model, chosen at random
    pool=sorted(i for i in slots[model] if i//RUN_SIZE==run);assert len(pool)==RUN_SIZE
    picks=rng.sample(pool,N)                                        # without replacement: a slot cannot be drawn twice
    assert len(set(picks))==N and all(i//RUN_SIZE==run for i in picks)
    selection[model]=[{'slot':i,'run':run,'run_slots':f'{run*RUN_SIZE:03d}-{run*RUN_SIZE+RUN_SIZE-1:03d}','artifact_id':f'{model}__t{i:02d}_c000'} for i in sorted(picks)]
for model in EXCLUDE:selection.pop(model)
GROUPS=('1','2','3');G=10
for model,rows in selection.items():          # rows are the random selection listed by slot; groups are consecutive tens
    for k,r in enumerate(rows):r['group']=GROUPS[k//G]
    assert sorted(collections.Counter(r['group'] for r in rows).values())==[G]*len(GROUPS)
now=datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
md=[f'# Sampling bots selected for final tournament',
    '',
    f'Selected {now}. Pool: `{POOL}` (SH-250 sampling harness, 23 models × 250 zero-shot samples). Excluded on request: {", ".join(sorted(EXCLUDE))}; the remaining {len(selection)} models are listed.',
    f'Rule: for each model, one of its five 50-slot runs (slots 000-049, 050-099, 100-149, 150-199, 200-249; the runs the pool\'s Top-Bot-per-Run round robin played inside) was chosen uniformly at random, then {N} of that run\'s 50 bots were drawn uniformly at random **without replacement** (a slot cannot be selected twice), with no filtering on validation, qualification or results. Every pairing inside a group therefore lies within one pool run.',
    f'Method: Python `random.Random(seed)`: `rng.choice(runs)` then `rng.sample(run_slots, {N})` per model, all 23 models processed in sorted order (the excluded models are drawn and then dropped, so the other models\' picks do not depend on the exclusion). Seed (generated by `secrets.randbits(64)`): `{seed}`. Re-run `python3 select_sampling_bots.py {seed}` to reproduce this exact list.',
    '',
    f'Slot `cNNN` under `samples/<model>/` is sample index NNN; its pool artifact id is `<model>__tNN_c000`. Total selected: {N*len(selection)} bots.',
    f'Groups: each model\'s {N} selected bots are split into {len(GROUPS)} groups of {G} in the order listed: rows 1-10 are group 1, rows 11-20 group 2, rows 21-30 group 3 (the selection itself is the random step). The group of every bot is in its table row, and each model section ends with the three group lists.',
    '']
for model,rows in selection.items():
    md.append(f'## {model}');md.append('');md.append(f'Pool run: `g{rows[0]["run"]}` (slots {rows[0]["run_slots"]})');md.append('');md.append('| # | slot | artifact id | group |');md.append('|--:|---|---|:-:|')
    for k,r in enumerate(rows,1):md.append(f"| {k} | c{r['slot']:03d} | `{r['artifact_id']}` | {r['group']} |")
    md.append('')
    for name in GROUPS:md.append(f"**Group {name}** ({G}): "+', '.join(f"`{r['artifact_id']}`" for r in rows if r['group']==name));md.append('')

(HERE/'sampling_bots_selected_for_final_tournament.md').write_text('\n'.join(md))
(HERE/'sampling_bots_selected_for_final_tournament.json').write_text(json.dumps({'pool':POOL,'per_model':N,'groups':{'names':list(GROUPS),'size':G,'rule':'consecutive tens of the listed selection'},'run_size':RUN_SIZE,'chosen_run':{m:chosen_run[m] for m in selection},'seed':seed,'selected_at':now,'selection':selection},indent=1))
print('seed',seed,'models',len(selection),'bots',sum(len(v) for v in selection.values()))
