function toolExperimentProgress(runs){
 const stoppedStates=new Set(['failed','stopped','error','blocked','incomplete']);
 return `<section id="tool-experiment-progress" aria-labelledby="tool-experiment-progress-title"><h3 id="tool-experiment-progress-title" class="figure-label">Experiment progress · tool use</h3><p class="muted small">${runs.length} runs in the selected repeat group. Bars show completed model turns; a run can finish successfully before using all ten turns.</p><div class="summary tool-progress-grid">${runs.map(run=>{
  const total=Number.isFinite(run.total_turns)&&run.total_turns>0?run.total_turns:10;
  const completed=Number.isFinite(run.completed_turns)?Math.max(0,run.completed_turns):0;
  const finished=run.status==='completed',stopped=stoppedStates.has(run.status);
  const pct=Math.min(100,100*completed/total),error=run.error_detail||run.error;
  const status=finished?(completed<total?`Completed · finished after ${completed} turns`:'Completed'):stopped?'Stopped · needs attention':run.status==='running'?`Running · turn ${run.turn||Math.min(completed+1,total)}${run.stage?' · '+run.stage:''}`:run.stage||run.status||'Waiting to start';
  const eta=finished?'Finished':stopped?'Stopped':duration(run.eta_seconds);
  return `<article class="panel tool-progress-card ${finished?'tool-progress-complete':stopped?'tool-progress-stopped':''}" data-tool-progress="${esc(run.id)}"><div class="cardhead"><h4>${esc(run.title||run.model||run.id)}</h4><strong>${completed}/${total}</strong></div><div class="bar" role="progressbar" aria-label="${esc(run.title||run.id)} · completed model turns" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${Math.min(completed,total)}" aria-valuetext="${completed} of ${total} model turns completed; ${esc(status)}"><div style="width:${pct}%"></div></div><p class="muted tool-progress-status">${esc(status)}</p>${!finished&&!stopped&&run.current_api_seconds!=null?`<p class="muted small">Current API call: ${duration(run.current_api_seconds)}</p>`:''}${error?`<details class="tool-progress-error"><summary>Run error details</summary><p>${esc(error)}</p></details>`:''}<div class="stats"><div><div class="label">ETA remaining</div><div class="value">${eta}</div></div><div><div class="label">API cost so far</div><div class="value">${dollars(run.cost_usd)}</div></div><div><div class="label">Tool calls</div><div class="value">${run.tool_calls??'—'}</div></div><div><div class="label">Saved bots</div><div class="value">${run.bots_produced??'—'}</div></div></div><p class="muted small">${finished?'Run finished':stopped?'Run stopped':'ETA covers API time; tool experiments and selection matches can add time.'}</p><button type="button" data-tool-progress-run="${esc(run.id)}" aria-label="View ${esc(run.title||run.id)}">${run.id===selectedToolRun?'Viewing this run':'View run'}</button></article>`;
 }).join('')}</div></section>`;
}
